stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jenkins
      pushRemote: true
      registry: easipoc.azurecr.io
timeout: 60
notification: {}
